# Generated by Django 5.1.7 on 2025-03-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='announcement_notification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='browser_notification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_relation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hours_worked',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_balance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_notification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='payslip_notification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='performance_rating',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='khan', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=255),
        ),
    ]
